name: scientific_programming
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - jupyter
  - nodejs
  - jupyterlab
  - ipywidgets
  - numpy
  - matplotlib
  - mpl_sample_data
  - pandas
  - statsmodels
  - seaborn
  - plotnine
  - pivottablejs
  - pandas-profiling
  - altair
  - vega_datasets
  - numba
  - pytest
  - cython
  - tqdm
  - pip:
    - expyriment
    - pygame
    - jupyterlab-solutions
    - jupyterlab_code_formatter
    - nb_black
    - ipympl
    - scikit-misc
    - pySerial
    - tqdm
    - clean_ipynb
